version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: hoge
    volumes:
      - hoge-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  hoge-db-data:
